FROM python:3.10-slim

# Instalujemy FFmpeg w chmurze, żeby konwersja wideo działała poprawnie
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

# Tworzymy bezpiecznego użytkownika
RUN useradd -m -u 1000 user
USER user
ENV HOME=/home/user \
    PATH=/home/user/.local/bin:$PATH

WORKDIR $HOME/app

# Kopiujemy zależności i je instalujemy
COPY --chown=user:user requirements.txt .
RUN pip install --no-cache-dir --user -r requirements.txt

# Kopiujemy resztę kodu aplikacji do kontenera
COPY --chown=user:user . $HOME/app

# Uruchomienie aplikacji na porcie wymaganym przez Render
CMD uvicorn main:app --host 0.0.0.0 --port ${PORT:-10000}